### ISSUE TITLE
RE: Five Years "Too Late" and Trying with a Fresh Fork/Seth

### ISSUE THREAD

**Issue by silver2row** [Seeed-Studio/MotorBridgeCapeFirmware#1]
Hello,

I still have a bunch of the Motor Bridge Capes. I was looking to get more but I am now thinking of figuring out how to compile and flash the M0 onboard the Motor Bridge Cape.

I found your source here. 

Nice!

Anyway, I am learning more and more about Cortex-M processors. I wanted to try to figure out something. mbed has a new compiler online and their site for the os.mbed.com/handbook/ is outdated/deprecated. 

...

So, I thought I would ask you a couple of questions:

    Is the only way to flash the chip onboard the Motor Bridge Cape done with the older version of mbed compilers?

and...

    Since the deprecation of the handbook, I am having some complications getting a new flash done for the Cortex-M0.

Anyway, if you have any pointers or ideas, I am all ears. 

Seth

**Comment by silver2row** [comment]
Hello Again Sir,

Basically, I am just trying to figure out how to compile/flash source on the M0, i.e. the Cortex-M0_f030r8.

Seth

P.S. It seems the old "make flash" command does not work any longer and I am trying to update it in case there are newer revisions one day of the Motor Bridge Cape.

**Comment by silver2row** [comment]
make flash
    ./script/flasher MotorBridgeCapeFirmware.bin
    /home/debian/BBG/MotorBridgeCapeFirmware
    ./script/flasher: 7: echo: echo: I/O error
    ./script/flasher: 8: echo: echo: I/O error
    ./script/flasher: 9: ./script/flasher: cannot create /sys/class/gpio/gpio49/dire                                                                   ction: 
    Directory nonexistent
    ./script/flasher: 10: ./script/flasher: cannot create /sys/class/gpio/gpio117/di                                                                   rection: 
    Directory nonexistent
    ./script/flasher: 12: ./script/flasher: cannot create /sys/class/gpio/gpio117/va                                                                   lue: 
    Directory nonexistent
    ./script/flasher: 14: ./script/flasher: cannot create /sys/class/gpio/gpio49/val                                                                   ue: 
    Directory nonexistent
    ./script/flasher: 15: ./script/flasher: cannot create /sys/class/gpio/gpio49/val                                                                   ue: 
    Directory nonexistent
    Reading data from MotorBridgeCapeFirmware.bin
    Can't init. Ensure BOOT0=1, BOOT1=0, and reset device
    Traceback (most recent call last):
      File "./script/stm32loader.py", line 555, in <module>
        bootversion = cmd.cmdGet()
      File "./script/stm32loader.py", line 141, in cmdGet
        if self.cmdGeneric(0x00):
      File "./script/stm32loader.py", line 138, in cmdGeneric
        return self._wait_for_ack(hex(cmd))
      File "./script/stm32loader.py", line 89, in _wait_for_ack
        raise CmdException("No response to %s" % info)
    __main__.CmdException: No response to 0x0
    ./script/flasher: 19: ./script/flasher: [1==0]: not found
    Reading data from MotorBridgeCapeFirmware.bin
    Can't init. Ensure BOOT0=1, BOOT1=0, and reset device
    Traceback (most recent call last):
      File "./script/stm32loader.py", line 555, in <module>
        bootversion = cmd.cmdGet()
      File "./script/stm32loader.py", line 141, in cmdGet
        if self.cmdGeneric(0x00):
      File "./script/stm32loader.py", line 138, in cmdGeneric
        return self._wait_for_ack(hex(cmd))
      File "./script/stm32loader.py", line 89, in _wait_for_ack
        raise CmdException("No response to %s" % info)
    __main__.CmdException: No response to 0x0
    haha
    ./script/flasher: 26: ./script/flasher: cannot create /sys/class/gpio/gpio117/value: Directory nonexistent
    ./script/flasher: 27: ./script/flasher: cannot create /sys/class/gpio/gpio49/value: Directory nonexistent
    ./script/flasher: 28: ./script/flasher: cannot create /sys/class/gpio/gpio49/value: Directory nonexistent
    make: *** [Makefile:200: flash] Error 2

Here are my errors. I think when I tried to write to the chip the info. got corrupted. Is there a known remedy for this `make flash` command?

Seth

**Comment by mvduin** [comment]
The flasher script is broken for current systems.  Try replacing the contents of script/flasher by:
```bash
#!/bin/bash

set -e

config-pin P9.23 gpio_pd >/dev/null  # gpio 1.17  reset
config-pin P9.25 gpio_pd >/dev/null  # gpio 3.21  boot0
config-pin P9.21 uart >/dev/null     # uart 2 txd
config-pin P9.22 uart >/dev/null     # uart 2 rxd

reset_gpio=1.17
boot0_gpio=3.21

gpio() {
	local -i gpio="${1/./*32+}"
	local attr="$2" value="$3"
	echo "$value" >"/sys/class/gpio/gpio$gpio/$attr"
}

gpio $reset_gpio direction low
gpio $boot0_gpio direction low

reset_stm() {
	local boot0="$1"
	gpio $reset_gpio value 0
	gpio $boot0_gpio value "$boot0"
	gpio $reset_gpio value 1
	sleep 0.2
}

reset_stm 1
python ./script/stm32loader.py -p /dev/ttyS2 -evw "$@"
reset_stm 0
```
and then run `make flash` again, after first rebooting if you've attempted to run the broken flash script since the last reboot (since it seems to break the gpios used).

**Comment by silver2row** [comment]
Hello,

That script @mvduin works just like you said it would work. Thank you, sir.

Seth
